### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by backspace**
I came across this in the course of #6, a tiny fix!

### CODE REVIEW

**Comment by samueljseay** [comment]
Hmm, what was I thinking when I wrote this comment.. I think the code should also have `:email` as the atom instead of `:submit`.. otherwise its just a confusing example...

**Comment by samueljseay** [comment]
So the full example:

```
 # with a collection
    defmodule MyPage do
      use PageObject
      collection :things, ".thing" do
        fillable :email, "input[type='email']"
      end
    end
    # fill input of 0th item in things
    |> MyPage.Things.get(0)
    MyPage.Things.email("demo@example.com")
```

**Comment by backspace** [comment]
hah indeed, I also wasn’t fully thinking with the initial commit. I’ve fixed it and force pushed. 😀

**Comment by samueljseay** [comment]
Awesome, thank you! 

@backspace If you're still keen to add the `is_visible` as a PR, then I'll do a release when that makes it in.

**Comment by backspace** [comment]
Will do! 🎉

**Pull request merged**
